### ISSUE TITLE
Cannot import project (Plugin [id: 'com.android.application'] was not found in any of the following sources)

### ISSUE THREAD

**Issue by Doctoror** [SCratORS/Everchanging#1]
Hi!

Only app module committed instead of the whole project.
The parent directory with root `build.gradle`, `settings.gradle` and `gradle` directory with `wrapper` is missing.

Please commit the parent directory of this directory.

**Comment by SCratORS** [comment]
Add in 'root_dir'

**Comment by Doctoror** [comment]
Thank you. But I meant something a bit different. Usually the repository starts with the directory that is a parent directory of a committed module, for example, see Google's Sunflower https://github.com/android/sunflower, or any of mine repositories. This allows maintainers to just check out and import the project without manually copying files to parent directory.
