### ISSUE TITLE
Textures are flickering

### ISSUE THREAD

**Issue by SCratORS** [SCratORS/Everchanging#24]
@Doctoror  After adding a [pool of  objects](https://github.com/SCratORS/Everchanging/pull/11), sometimes the textures of objects do not behave correctly. The pattern cannot be identified.
See video. On the top left, the object is flickering

https://drive.google.com/file/d/1SCpNntTLlb-Bd4bSRL0FziacO6DFEc4F

This behavior is also seen in the animation of "butterflies". I assume that on all the others too.

And he constantly writes an error in the logcat, see
https://drive.google.com/file/d/1l9FUN4OyexqiG3BRqd0repV6erBvzEBd

**Comment by Doctoror** [comment]
I will take a look.

**Comment by Doctoror** [comment]
I don't have this error. Are you above to reproduce it every time?
Are you sure it is occurring only for builds with pull of objects?

Unfortunately, I cannot reproduce the error.
Maybe it's a problem with device state?

If I Google it I get only cryptic bug reports for Flutter:
https://www.google.com/search?q=%22ioctl+err%3A+1%22

**Comment by SCratORS** [comment]
I do not know why this is happening. this became possible after adding a pool of objects. It is suspected that this is due to the removal of the object from the pool. for example, on petals, sometimes one object starts playing in a circle, although it should have been deleted. It's easy to spot on the new TouchBlock animation. after releasing your finger from the screen, all TouchBlock animations should end, but they continue to appear for some time.

**Comment by Doctoror** [comment]
Maybe the error is not related. I will try to reproduce with touch blick and let you know what I find.

**Comment by Doctoror** [comment]
I could reproduce with Petals now, I see it. No errors in LogCat. This was unrelated.

**Comment by Doctoror** [comment]
I found the issue. `ObjectPool:111` may return an item that is used because it iterates at `ObjectPool:109` past `limit`.

**Comment by SCratORS** [comment]
yes, most likely the error in the log is not related to the pool. it seems to be a local error on my device
