### ISSUE TITLE
Supplied proguard configuration does not exist

### ISSUE THREAD

**Issue by Doctoror** [SCratORS/Everchanging#29]
When I try to build with `inifyEnabled true` I get

```
> Task :app:minifyDebugWithR8
Supplied proguard configuration does not exist: .../app/proguard-rules.pro
```

This is because your `proguard-rules.pro` was never committed.
I can add mine with empty config but I don't know if you had any custom rules defined there so I wanted to ask first.
Or you can add and merge it yourself.

**Comment by SCratORS** [comment]
I didn't make any changes there.
