### ISSUE TITLE
Should this wallpaper change background  throughout the day?


### ISSUE THREAD

**Issue by mrtaxi** [SCratORS/Everchanging#42]
Hi! 
Thank you for these awesome wallpapers!
Should this wallpaper change background  throughout the day?  After installation, I even saw two eyes once.  But now it’s just a green background and flying dandelion seeds.  All permits have been allowed.  I reinstalled it twice.
Android 13, OnePlus Ace 2 Pro.

**Comment by SCratORS** [comment]
Hi! They change, but there are different animations on different days. On average, animations last 2 hours. The background changes every 10 days.
You can study the source code. Here there is a table of the day, time and animations. [here](https://github.com/SCratORS/Everchanging/blob/main/app/src/main/java/com/scrat/everchanging/EverchangingRender.java)

**Comment by mrtaxi** [comment]
Thank you for the information!  I can't stop watching.  The wallpaper fascinates with its mystic beauty. Great job!

**Comment by SCratORS** [comment]
Thank you, too. Use it with pleasure!
